### ISSUE TITLE
Problems With the script...

### ISSUE THREAD

**Issue by mud1t** [pierrrrrrre/PyGeoIpMap#6]
I put the script in/usr/local/bin with +chmod and it's happening again and again and I've Maxmind GeoLite2.csv , results.csv are IPs and I m a n00b , sorry for my errors :-)
$ pygeoipmap.py -i /root/results3.csv -o /tmp/output.png -f csv -s m --db /home/jhk/GeoLite2-City-Locations.csv
Traceback (most recent call last):
  File "/usr/local/bin/pygeoipmap.py", line 124, in <module>
    main()
  File "/usr/local/bin/pygeoipmap.py", line 118, in main
    lats, lons = get_lat_lon_from_csv(args.input)
  File "/usr/local/bin/pygeoipmap.py", line 77, in get_lat_lon_from_csv
    lats.append(row[-2])
IndexError: list index out of range

I also did  $ python pygeoipmap.py -i /root/results3.csv -o /tmp/output.png -f csv -s m --db /home/jhk/GeoLite2-City-Locations.csv
python: can't open file 'pygeoipmap.py': [Errno 2] No such file or directory

**Comment by pierrrrrrre** [comment]
Hi,

it looks like the data you provide is not what the script expects. A few things to investigate on your side:

- try using the binary GeoLite database instead of the CSV one. It is available [here](http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz) (you have to unzip it).
- the error that pops up is because `lats.append(row[-2])` is looking for the second element from the end of the line. I put [a few examples](https://github.com/pierrrrrrre/PyGeoIpMap/blob/master/pygeoipmap.py#L68-72) in the comments of the code. It looks like you don't have the data in the right form in your `results3.csv` file. From what you're telling me, I think you should try with the `-f ip` argument instead of `-f csv`.

Check it out and let me know if it works! :)

**Comment by mud1t** [comment]
should i move GeoLiteCity.dat  to /usr/local/share/GeoIP??

**Comment by pierrrrrrre** [comment]
Put it wherever you want and just point to the right path when you call it. If you put it in /home/jhk/GeoLiteCity.dat, just call the script with `-f ip -s m --db /home/jhk/GeoLiteCity.dat`.

**Comment by mud1t** [comment]
ok. Olympus thanks to you...
I'll report it back as soon as i successfully run it..
Amazing work.. :-)

**Comment by mud1t** [comment]
Worked perfectly... :+1: :100:

**Comment by pierrrrrrre** [comment]
Cool, glad to know it worked!

Enjoy ;)

**Comment by antoncedoni** [comment]
python pygeoipmap.py /tmp/ip_list

pygeoipmap.py: error: unrecognized arguments: /tmp/ip_list

**Comment by pierrrrrrre** [comment]
Hi @antoncedoni, the previous issue looks different from yours and has been closed.

Can you open a separate one and provide the following info:

- operating system you're using
- version of Python you're running

Also, can you check if your `ip_list` file follows the [format described in the readme file](https://github.com/pierrrrrrre/PyGeoIpMap#using-a-list-of-ip-addresses-and-the-freegeoip-web-service)?

Thanks,
